FROM mhart/alpine-node:6.11.4
LABEL maintainer="digitalpulp"

COPY entrypoint.sh /usr/local/bin/
RUN apk add --no-cache make gcc g++ python git && chmod ugo=rx /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
